"""Initial migration

Revision ID: abf53b7486c8
Revises: 
Create Date: 2026-06-03 12:05:58.534152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abf53b7486c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.drop_table('machines')
    op.drop_index(op.f('ix_owner_workflows_vehicle_number'), table_name='owner_workflows')
    op.drop_index(op.f('ix_owner_workflows_owner_phone'), table_name='owner_workflows')
    op.drop_table('owner_workflows')
    op.drop_index(op.f('ix_driver_workflows_workflow_status'), table_name='driver_workflows')
    op.drop_index(op.f('ix_driver_workflows_vehicle_number'), table_name='driver_workflows')
    op.drop_index(op.f('ix_driver_workflows_owner_phone'), table_name='driver_workflows')
    op.drop_index(op.f('ix_driver_workflows_driver_phone'), table_name='driver_workflows')
    op.drop_table('driver_workflows')
    
    # Drop other tables
    op.drop_table('solutions')
    op.drop_index(op.f('ix_conversation_states_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_phone_number'), table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_table('problems')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_fleet_conversations_id'), table_name='fleet_conversations')
    op.drop_index(op.f('ix_fleet_conversations_phone'), table_name='fleet_conversations')
    op.drop_table('fleet_conversations')
    op.drop_index(op.f('ix_vehicle_monitoring_status'), table_name='vehicle_monitoring')
    op.drop_index(op.f('ix_vehicle_monitoring_vehicle_number'), table_name='vehicle_monitoring')
    op.drop_table('vehicle_monitoring')
    op.drop_index(op.f('ix_vehicle_contacts_contact_type'), table_name='vehicle_contacts')
    op.drop_index(op.f('ix_vehicle_contacts_driver_phone'), table_name='vehicle_contacts')
    op.drop_index(op.f('ix_vehicle_contacts_owner_phone'), table_name='vehicle_contacts')
    op.drop_index(op.f('ix_vehicle_contacts_vehicle_number'), table_name='vehicle_contacts')
    op.drop_index(op.f('ux_vehicle_contacts_unique'), table_name='vehicle_contacts')
    op.drop_table('vehicle_contacts')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_vehicle_statuses_id'), table_name='vehicle_statuses')
    op.drop_table('vehicle_statuses')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('machines_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('machines_pkey')),
    sa.UniqueConstraint('serial_number', name=op.f('machines_serial_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('owner_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('workflow_status', sa.VARCHAR(length=50), server_default=sa.text("'IN_PROGRESS'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('current_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('issue_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('assigned_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('assigned_contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('driver_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('owner_workflows_pkey'))
    )
    op.create_index(op.f('ix_owner_workflows_vehicle_number'), 'owner_workflows', ['vehicle_number'], unique=False)
    op.create_index(op.f('ix_owner_workflows_owner_phone'), 'owner_workflows', ['owner_phone'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bot_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'driver'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('phone', name=op.f('users_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('driver_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('driver_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('workflow_status', sa.VARCHAR(length=50), server_default=sa.text("'IN_PROGRESS'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('current_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('issue_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('estimated_arrival_time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('troubleshooting_started', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('driver_workflows_pkey'))
    )
    op.create_index(op.f('ix_driver_workflows_workflow_status'), 'driver_workflows', ['workflow_status'], unique=False)
    op.create_index(op.f('ix_driver_workflows_vehicle_number'), 'driver_workflows', ['vehicle_number'], unique=False)
    op.create_index(op.f('ix_driver_workflows_owner_phone'), 'driver_workflows', ['owner_phone'], unique=False)
    op.create_index(op.f('ix_driver_workflows_driver_phone'), 'driver_workflows', ['driver_phone'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('vehicles_driver_id_fkey')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('vehicles_manager_id_fkey')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('vehicles_supervisor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey')),
    sa.UniqueConstraint('vehicle_number', name=op.f('vehicles_vehicle_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('vehicle_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ign_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_gps_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('not_working_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_statuses_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_statuses_pkey')),
    sa.UniqueConstraint('vehicle_id', name=op.f('vehicle_statuses_vehicle_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vehicle_statuses_id'), 'vehicle_statuses', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('alerts_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tickets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tickets_pkey'))
    )
    op.create_table('vehicle_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('driver_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_contacts_pkey'))
    )
    op.create_index(op.f('ux_vehicle_contacts_unique'), 'vehicle_contacts', ['vehicle_number', 'owner_phone', 'driver_phone', 'contact_type'], unique=True)
    op.create_index(op.f('ix_vehicle_contacts_vehicle_number'), 'vehicle_contacts', ['vehicle_number'], unique=False)
    op.create_index(op.f('ix_vehicle_contacts_owner_phone'), 'vehicle_contacts', ['owner_phone'], unique=False)
    op.create_index(op.f('ix_vehicle_contacts_driver_phone'), 'vehicle_contacts', ['driver_phone'], unique=False)
    op.create_index(op.f('ix_vehicle_contacts_contact_type'), 'vehicle_contacts', ['contact_type'], unique=False)
    op.create_table('vehicle_monitoring',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('vehicle_imei', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('driver_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('driver_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issue_detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ticket_created', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_monitoring_pkey'))
    )
    op.create_index(op.f('ix_vehicle_monitoring_vehicle_number'), 'vehicle_monitoring', ['vehicle_number'], unique=False)
    op.create_index(op.f('ix_vehicle_monitoring_status'), 'vehicle_monitoring', ['status'], unique=False)
    op.create_table('fleet_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fleet_conversations_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fleet_conversations_pkey'))
    )
    op.create_index(op.f('ix_fleet_conversations_phone'), 'fleet_conversations', ['phone'], unique=False)
    op.create_index(op.f('ix_fleet_conversations_id'), 'fleet_conversations', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_table('problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('machine_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('problems_pkey'))
    )
    op.create_table('conversation_states',
    sa.Column('legacy_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('context_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_states_pkey'))
    )
    op.create_index(op.f('ix_conversation_states_phone_number'), 'conversation_states', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversation_states_id'), 'conversation_states', ['legacy_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('solutions_problem_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('solutions_pkey'))
    )
    # ### end Alembic commands ###
